TESTED request

### Index method

GET http://localhost:4000/api/wine_listings

### Successfully creates a wine listing
### Response = 201 Created

POST http://localhost:4000/api/wine_listings
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM2MTY1NywiZXhwIjoxNjU5NDQ4MDU3LCJqdGkiOiIzYzM1MDg0YS0zMWU3LTRiMDItODMzNS0wYTkzOGYxODMxZDYifQ.vwQK9pe5hixTcL2MxrMGfmnCCQXgh4eghLY9VG14Jns

{
    "brand": "Testing Wine id 8",
    "grape_variety": "Testing Wine id 8",
    "year": "2020",
    "category": "Red",
    "country": "Australia",
    "region": "Geelong",
    "description": "Great deep colour, and sweet spice aromas, with a much firmer palate than we see in the Sangreal. These wines have a perfect fade from fruit to structure, a velvet like character, really complex texture. It’s darker, firmer edged and more upright. You can taste a fresher fruit note, black cherries and plums and a sense of fine oak. Really impressive."
}

### Testing for regular users trying to create wine listing when not allowed because regular user does not have same rights as admin users
### JWT below was given when a regular user logged in
POST http://localhost:4000/api/wine_listings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM2NDcwNywiZXhwIjoxNjU5NDUxMTA3LCJqdGkiOiI3NjMwNDhjNC0yMTUxLTQwY2ItODFlZS1jZDgwNWIyOTAyYzIifQ.Jqs21IjodMTJXzpag--NOmF0x_Eq91nj1Kk7V4TCE8g

{
    "brand": "Testing for regular using trying to create wine listing when not allowed because regular user does not have same rights as admin users. This should fail",
    "grape_variety": "Pinot Noir",
    "year": "2020",
    "category": "Red",
    "country": "Australia",
    "region": "Geelong",
    "description": "description for testing purposes only."
}

### Unsuccessfully posts a wine_listing.
### Not providing Authorization bearer
### Not providing all details required.
### Response = 422 Unprocessable Entity
POST http://localhost:4000/api/wine_listings
Content-Type: application/json

{
    "brand": ""
}

### show wine_listing id: 2
GET http://localhost:4000/api/wine_listings/2

### unsuccessfully show wine_listings id: 1000
### Response = 404 Not Found
GET http://localhost:4000/api/wine_listings/1000

### The purpose of this test is to ensure that user must be logged in as Admin to be able to UPDATE wine listings
### Response = 401 Unauthorized
### Currently DOES NOT work without Authorization: Bearer 
PUT http://localhost:4000/api/wine_listings/6
Content-Type: application/json

{
    "brand": "test for successfully updating id: 6 without Authorization bearer secret key",
    "grape_variety": "test for successfully updating id: 6",
    "year": "2022",
    "category": "test for successfully updating id: 6",
    "country": "test for successfully updating id: 6",
    "region": "test for successfully updating id: 6",
    "description": "test for successfully updating id: 6"
}


### Testing UPDATE for Admin
### Test as Admin user with params performing updates to wine listing id:
### Test inlcudes jwt
PUT http://localhost:4000/api/wine_listings/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM1NDA2NiwiZXhwIjoxNjU5NDQwNDY2LCJqdGkiOiJjOGE0YTI0Mi1hZTY0LTQyZDMtYjI1YS04MjAzYzU1ODQxMjMifQ.BImjf2-sLtZTJvAVqHq0jk9tXDKrFxPjEMQfImJknLI

{
    "brand": "test for successfully updating id:3 ONLY, as an admin with correct params & JWT",
    "grape_variety": "test update id 2",
    "year": "2022",
    "category": "test update id 2",
    "country": "test update id 2",
    "region": "test update id 2",
    "description": "test update id 2"
}

### Successful testing of
### a fail attempt for regular user, who is logged in, performing an update of wine listings
### response = 204 No Content
PUT http://localhost:4000/api/wine_listings/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM0MjU3MywiZXhwIjoxNjU5NDI4OTczLCJqdGkiOiIxMTI4ZTI5My02NDE0LTRhZTctYTY2NC1jNWUxOTJhODM1YjAifQ.R5JhlDBx35rDxjll7ZzAp-3BvKeBLBwpVY5WMLMghhg

{
    "brand": "test for updating id: 4, with Auth bearer token as a regular user. This is expected to fail",
    "grape_variety": "test",
    "year": "2022",
    "category": "test",
    "country": "test",
    "region": "test",
    "description": "test"
}

### NEEDS testing
### As a regular user attempting to update wine_listing id 4
PUT http://localhost:4000/api/wine_listings/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM0MjU3MywiZXhwIjoxNjU5NDI4OTczLCJqdGkiOiIxMTI4ZTI5My02NDE0LTRhZTctYTY2NC1jNWUxOTJhODM1YjAifQ.R5JhlDBx35rDxjll7ZzAp-3BvKeBLBwpVY5WMLMghhg

{
    "brand": "test for updating id: 4, with Auth bearer token as a regular user. expect to fail",
    "grape_variety": "test",
    "year": "2022",
    "category": "test",
    "country": "test",
    "region": "test",
    "description": "test"
}

### Currently Testing for Admin to delete wine listing id
### !!!Currently able to delete without Authorization Bearer of secret key!!!
### Response = 204 :no_content
DELETE http://localhost:4000/api/wine_listings/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM2MTY1NywiZXhwIjoxNjU5NDQ4MDU3LCJqdGkiOiIzYzM1MDg0YS0zMWU3LTRiMDItODMzNS0wYTkzOGYxODMxZDYifQ.vwQK9pe5hixTcL2MxrMGfmnCCQXgh4eghLY9VG14Jns

### Intentionally, Unsucessfully delete wine_listings id: 1000
### Response = 500 :internal_server_error
DELETE http://localhost:4000/api/wine_listings/1000

# --------------------------------------------------

### Access member data
### Pass 
GET http://localhost:4000/member-data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwic2NwIjoidXNlciIsImF1ZCI6bnVsbCwiaWF0IjoxNjU4NTYwMTU3LCJleHAiOjE2NTg1NjM3NTcsImp0aSI6IjkxNjRlNzY1LTAwMzktNDk2Ny1hZWI5LTJkYjc3OTgyOGI0NyJ9.MeM_CqfGUUuk8N1nKRowKbDEEcNBsMtfqWg_A4QBs9s

### THIS TEST IS NOT WORKING AS EXPECTED!!!
### Create user with only 2 params - email and password - Should FAIL
POST http://localhost:4000/api/sign_up
Content-Type: application/json

{  
    "user": {
        "email": "jacqui2@test.com",
        "password": "password10"
    }
}

### Create user
### 4 Params given - username, email, password, password_confirmation
POST http://localhost:4000/api/sign_up
Content-Type: application/json

{  
    "user": {
        "username": "testtime",
        "email": "mrtest@test.com",
        "password": "password",
        "password_confirmation": "password"
    }
}


### Login with correct details
### PASS with correct details
POST http://localhost:4000/api/login
Content-Type: application/json

{  
    "user": {
        "email": "mrtest@test.com",
        "password": "password"
    }
}

### LogOUT while logged in with a jwt auth token
### PASS with token from the login session
DELETE http://localhost:4000/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM2MTY1NywiZXhwIjoxNjU5NDQ4MDU3LCJqdGkiOiIzYzM1MDg0YS0zMWU3LTRiMDItODMzNS0wYTkzOGYxODMxZDYifQ.vwQK9pe5hixTcL2MxrMGfmnCCQXgh4eghLY9VG14Jns

### Test for current user is admin?
### This test might need to be ran with rspec



###Not yet tested

### ADMIN section

### Create Admin user
POST http://localhost:4000/api/sign_up
Content-Type: application/json

{  
    "user": {
        "email": "admin1@gmail.com",
        "password": "password1"
    }
}



### ----------------------------------------------
### CATEGORY NOT YET TESTED

### Get categories

GET http://localhost:4000/api/categories


### ----------------------------------------------
### COMMENTS TESTS ALL PASSED


### Gets all comments
### Passes with 200 response
GET http://localhost:4000/comments
Content-Type: application/json


### Create comment
### Passes with 201 created response if user signed in with token
### Returns 401 if not signed in
POST http://localhost:4000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTQwODczMSwiZXhwIjoxNjU5NDk1MTMxLCJqdGkiOiIxMmU1YjM0Zi0xYWRkLTQyMTItOTYzOC1lMjIxYmY0MWNjYTAifQ.V5WvayMyBnYgpKeIdTl_k81z6pgckN9khjDgfKj4OsA

{  
    "comment": {
        "user_comment": "Test comment 1",
        "user_id": 12,
        "wine_listing_id": 1
    }
}

### Create comment
### Passes with 201 created response
POST http://localhost:4000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTQwODczMSwiZXhwIjoxNjU5NDk1MTMxLCJqdGkiOiIxMmU1YjM0Zi0xYWRkLTQyMTItOTYzOC1lMjIxYmY0MWNjYTAifQ.V5WvayMyBnYgpKeIdTl_k81z6pgckN9khjDgfKj4OsA

{  
    "comment": {
        "user_comment": "Test comment 2",
        "user_id": 12,
        "wine_listing_id": 1
    }
}

### Create comment with no content in user_comment
### Passes with 422 unprocessable entity - user comment can't be blank
POST http://localhost:4000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTQwODczMSwiZXhwIjoxNjU5NDk1MTMxLCJqdGkiOiIxMmU1YjM0Zi0xYWRkLTQyMTItOTYzOC1lMjIxYmY0MWNjYTAifQ.V5WvayMyBnYgpKeIdTl_k81z6pgckN9khjDgfKj4OsA

{  
    "comment": {
        "user_comment": "",
        "user_id": 12,
        "wine_listing_id": 1
    }
}

### Update comment
### Passes with 200 response
PATCH http://localhost:4000/comments/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM5OTUwOCwiZXhwIjoxNjU5NDg1OTA4LCJqdGkiOiJiMDZkZDBkZC0zMTRiLTQwODItOTBiYy1kYjIwYjc2MTI2MzcifQ.y12cXmWH8RBaYnRsEewMM7J8F8afZQFTq1wC3xM8Dd0

{  
    "comment": {
        "id": 16,
        "user_comment": "Test comment 1 has been updated",
        "user_id": 12,
        "wine_listing_id": 1
    }
}

### Delete own comment
### Passes with 204 no content response
DELETE  http://localhost:4000/comments/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM5OTUwOCwiZXhwIjoxNjU5NDg1OTA4LCJqdGkiOiJiMDZkZDBkZC0zMTRiLTQwODItOTBiYy1kYjIwYjc2MTI2MzcifQ.y12cXmWH8RBaYnRsEewMM7J8F8afZQFTq1wC3xM8Dd0

{  
    "comment": {
        "id": 17,
        "user_comment": "Test comment 1",
        "user_id": 12,
        "wine_listing_id": 1
    }
}

### Delete another users comment
### Passes with 200 - error of unauthorised action
DELETE  http://localhost:4000/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMiIsInNjcCI6InVzZXIiLCJhdWQiOm51bGwsImlhdCI6MTY1OTM5OTUwOCwiZXhwIjoxNjU5NDg1OTA4LCJqdGkiOiJiMDZkZDBkZC0zMTRiLTQwODItOTBiYy1kYjIwYjc2MTI2MzcifQ.y12cXmWH8RBaYnRsEewMM7J8F8afZQFTq1wC3xM8Dd0

{  
    "comment": {
        "id": 1,
        "user_comment": "Test comment 1",
        "user_id": 12,
        "wine_listing_id": 1
    }
}